#pragma once

#include <array>
#include <optional>

namespace version_table {
    struct entry {
        int version;    
        char ec_level;
        int total_data;
        int ec_per_block;
        int blocks_in_grp_1;
        int size_of_grp_1_blocks;
        int blocks_in_grp_2;
        int size_of_grp_2_blocks;
    };

    constexpr const std::array<entry, 40> high_table = {
        entry{.version = 1, .ec_level = 'H', .total_data = 9, .ec_per_block = 17, .blocks_in_grp_1 = 1, .size_of_grp_1_blocks = 9, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 2, .ec_level = 'H', .total_data = 16, .ec_per_block = 28, .blocks_in_grp_1 = 1, .size_of_grp_1_blocks = 16, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 3, .ec_level = 'H', .total_data = 26, .ec_per_block = 22, .blocks_in_grp_1 = 2, .size_of_grp_1_blocks = 13, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 4, .ec_level = 'H', .total_data = 36, .ec_per_block = 16, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 9, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 5, .ec_level = 'H', .total_data = 46, .ec_per_block = 22, .blocks_in_grp_1 = 2, .size_of_grp_1_blocks = 11, .blocks_in_grp_2 = 2, .size_of_grp_2_blocks = 12},
        entry{.version = 6, .ec_level = 'H', .total_data = 60, .ec_per_block = 28, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 15, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 7, .ec_level = 'H', .total_data = 66, .ec_per_block = 26, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 13, .blocks_in_grp_2 = 1, .size_of_grp_2_blocks = 14},
        entry{.version = 8, .ec_level = 'H', .total_data = 86, .ec_per_block = 26, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 14, .blocks_in_grp_2 = 2, .size_of_grp_2_blocks = 15},
        entry{.version = 9, .ec_level = 'H', .total_data = 100, .ec_per_block = 24, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 12, .blocks_in_grp_2 = 4, .size_of_grp_2_blocks = 13},
        entry{.version = 10, .ec_level = 'H', .total_data = 122, .ec_per_block = 28, .blocks_in_grp_1 = 6, .size_of_grp_1_blocks = 15, .blocks_in_grp_2 = 2, .size_of_grp_2_blocks = 16},
        entry{.version = 11, .ec_level = 'H', .total_data = 140, .ec_per_block = 24, .blocks_in_grp_1 = 3, .size_of_grp_1_blocks = 12, .blocks_in_grp_2 = 8, .size_of_grp_2_blocks = 13},
        entry{.version = 12, .ec_level = 'H', .total_data = 158, .ec_per_block = 28, .blocks_in_grp_1 = 7, .size_of_grp_1_blocks = 14, .blocks_in_grp_2 = 4, .size_of_grp_2_blocks = 15},
        entry{.version = 13, .ec_level = 'H', .total_data = 180, .ec_per_block = 22, .blocks_in_grp_1 = 12, .size_of_grp_1_blocks = 11, .blocks_in_grp_2 = 4, .size_of_grp_2_blocks = 12},
        entry{.version = 14, .ec_level = 'H', .total_data = 197, .ec_per_block = 24, .blocks_in_grp_1 = 11, .size_of_grp_1_blocks = 12, .blocks_in_grp_2 = 5, .size_of_grp_2_blocks = 13},
        entry{.version = 15, .ec_level = 'H', .total_data = 223, .ec_per_block = 24, .blocks_in_grp_1 = 11, .size_of_grp_1_blocks = 12, .blocks_in_grp_2 = 7, .size_of_grp_2_blocks = 13},
        entry{.version = 16, .ec_level = 'H', .total_data = 253, .ec_per_block = 30, .blocks_in_grp_1 = 3, .size_of_grp_1_blocks = 15, .blocks_in_grp_2 = 13, .size_of_grp_2_blocks = 16},
        entry{.version = 17, .ec_level = 'H', .total_data = 283, .ec_per_block = 28, .blocks_in_grp_1 = 2, .size_of_grp_1_blocks = 14, .blocks_in_grp_2 = 17, .size_of_grp_2_blocks = 15},
        entry{.version = 18, .ec_level = 'H', .total_data = 313, .ec_per_block = 28, .blocks_in_grp_1 = 2, .size_of_grp_1_blocks = 14, .blocks_in_grp_2 = 19, .size_of_grp_2_blocks = 15},
        entry{.version = 19, .ec_level = 'H', .total_data = 341, .ec_per_block = 26, .blocks_in_grp_1 = 9, .size_of_grp_1_blocks = 13, .blocks_in_grp_2 = 16, .size_of_grp_2_blocks = 14},
        entry{.version = 20, .ec_level = 'H', .total_data = 385, .ec_per_block = 28, .blocks_in_grp_1 = 15, .size_of_grp_1_blocks = 15, .blocks_in_grp_2 = 10, .size_of_grp_2_blocks = 16},
        entry{.version = 21, .ec_level = 'H', .total_data = 406, .ec_per_block = 30, .blocks_in_grp_1 = 19, .size_of_grp_1_blocks = 16, .blocks_in_grp_2 = 6, .size_of_grp_2_blocks = 17},
        entry{.version = 22, .ec_level = 'H', .total_data = 442, .ec_per_block = 24, .blocks_in_grp_1 = 34, .size_of_grp_1_blocks = 13, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 23, .ec_level = 'H', .total_data = 464, .ec_per_block = 30, .blocks_in_grp_1 = 16, .size_of_grp_1_blocks = 15, .blocks_in_grp_2 = 14, .size_of_grp_2_blocks = 16},
        entry{.version = 24, .ec_level = 'H', .total_data = 514, .ec_per_block = 30, .blocks_in_grp_1 = 30, .size_of_grp_1_blocks = 16, .blocks_in_grp_2 = 2, .size_of_grp_2_blocks = 17},
        entry{.version = 25, .ec_level = 'H', .total_data = 538, .ec_per_block = 30, .blocks_in_grp_1 = 22, .size_of_grp_1_blocks = 15, .blocks_in_grp_2 = 13, .size_of_grp_2_blocks = 16},
        entry{.version = 26, .ec_level = 'H', .total_data = 596, .ec_per_block = 30, .blocks_in_grp_1 = 33, .size_of_grp_1_blocks = 16, .blocks_in_grp_2 = 4, .size_of_grp_2_blocks = 17},
        entry{.version = 27, .ec_level = 'H', .total_data = 628, .ec_per_block = 30, .blocks_in_grp_1 = 12, .size_of_grp_1_blocks = 15, .blocks_in_grp_2 = 28, .size_of_grp_2_blocks = 16},
        entry{.version = 28, .ec_level = 'H', .total_data = 661, .ec_per_block = 30, .blocks_in_grp_1 = 11, .size_of_grp_1_blocks = 15, .blocks_in_grp_2 = 31, .size_of_grp_2_blocks = 16},
        entry{.version = 29, .ec_level = 'H', .total_data = 701, .ec_per_block = 30, .blocks_in_grp_1 = 19, .size_of_grp_1_blocks = 15, .blocks_in_grp_2 = 26, .size_of_grp_2_blocks = 16},
        entry{.version = 30, .ec_level = 'H', .total_data = 745, .ec_per_block = 30, .blocks_in_grp_1 = 23, .size_of_grp_1_blocks = 15, .blocks_in_grp_2 = 25, .size_of_grp_2_blocks = 16},
        entry{.version = 31, .ec_level = 'H', .total_data = 793, .ec_per_block = 30, .blocks_in_grp_1 = 23, .size_of_grp_1_blocks = 15, .blocks_in_grp_2 = 28, .size_of_grp_2_blocks = 16},
        entry{.version = 32, .ec_level = 'H', .total_data = 845, .ec_per_block = 30, .blocks_in_grp_1 = 19, .size_of_grp_1_blocks = 15, .blocks_in_grp_2 = 35, .size_of_grp_2_blocks = 16},
        entry{.version = 33, .ec_level = 'H', .total_data = 901, .ec_per_block = 30, .blocks_in_grp_1 = 11, .size_of_grp_1_blocks = 15, .blocks_in_grp_2 = 46, .size_of_grp_2_blocks = 16},
        entry{.version = 34, .ec_level = 'H', .total_data = 961, .ec_per_block = 30, .blocks_in_grp_1 = 59, .size_of_grp_1_blocks = 16, .blocks_in_grp_2 = 1, .size_of_grp_2_blocks = 17},
        entry{.version = 35, .ec_level = 'H', .total_data = 986, .ec_per_block = 30, .blocks_in_grp_1 = 22, .size_of_grp_1_blocks = 15, .blocks_in_grp_2 = 41, .size_of_grp_2_blocks = 16},
        entry{.version = 36, .ec_level = 'H', .total_data = 1054, .ec_per_block = 30, .blocks_in_grp_1 = 2, .size_of_grp_1_blocks = 15, .blocks_in_grp_2 = 64, .size_of_grp_2_blocks = 16},
        entry{.version = 37, .ec_level = 'H', .total_data = 1096, .ec_per_block = 30, .blocks_in_grp_1 = 24, .size_of_grp_1_blocks = 15, .blocks_in_grp_2 = 46, .size_of_grp_2_blocks = 16},
        entry{.version = 38, .ec_level = 'H', .total_data = 1142, .ec_per_block = 30, .blocks_in_grp_1 = 42, .size_of_grp_1_blocks = 15, .blocks_in_grp_2 = 32, .size_of_grp_2_blocks = 16},
        entry{.version = 39, .ec_level = 'H', .total_data = 1222, .ec_per_block = 30, .blocks_in_grp_1 = 10, .size_of_grp_1_blocks = 15, .blocks_in_grp_2 = 67, .size_of_grp_2_blocks = 16},
        entry{.version = 40, .ec_level = 'H', .total_data = 1276, .ec_per_block = 30, .blocks_in_grp_1 = 20, .size_of_grp_1_blocks = 15, .blocks_in_grp_2 = 61, .size_of_grp_2_blocks = 16},
    };
    constexpr const std::array<entry, 40> low_table = {
        entry{.version = 1, .ec_level = 'L', .total_data = 19, .ec_per_block = 7, .blocks_in_grp_1 = 1, .size_of_grp_1_blocks = 19, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 2, .ec_level = 'L', .total_data = 34, .ec_per_block = 10, .blocks_in_grp_1 = 1, .size_of_grp_1_blocks = 34, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 3, .ec_level = 'L', .total_data = 55, .ec_per_block = 15, .blocks_in_grp_1 = 1, .size_of_grp_1_blocks = 55, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 4, .ec_level = 'L', .total_data = 80, .ec_per_block = 20, .blocks_in_grp_1 = 1, .size_of_grp_1_blocks = 80, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 5, .ec_level = 'L', .total_data = 108, .ec_per_block = 26, .blocks_in_grp_1 = 1, .size_of_grp_1_blocks = 108, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 6, .ec_level = 'L', .total_data = 136, .ec_per_block = 18, .blocks_in_grp_1 = 2, .size_of_grp_1_blocks = 68, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 7, .ec_level = 'L', .total_data = 156, .ec_per_block = 20, .blocks_in_grp_1 = 2, .size_of_grp_1_blocks = 78, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 8, .ec_level = 'L', .total_data = 194, .ec_per_block = 24, .blocks_in_grp_1 = 2, .size_of_grp_1_blocks = 97, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 9, .ec_level = 'L', .total_data = 232, .ec_per_block = 30, .blocks_in_grp_1 = 2, .size_of_grp_1_blocks = 116, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 10, .ec_level = 'L', .total_data = 274, .ec_per_block = 18, .blocks_in_grp_1 = 2, .size_of_grp_1_blocks = 68, .blocks_in_grp_2 = 2, .size_of_grp_2_blocks = 69},
        entry{.version = 11, .ec_level = 'L', .total_data = 324, .ec_per_block = 20, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 81, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 12, .ec_level = 'L', .total_data = 370, .ec_per_block = 24, .blocks_in_grp_1 = 2, .size_of_grp_1_blocks = 92, .blocks_in_grp_2 = 2, .size_of_grp_2_blocks = 93},
        entry{.version = 13, .ec_level = 'L', .total_data = 428, .ec_per_block = 26, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 107, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 14, .ec_level = 'L', .total_data = 461, .ec_per_block = 30, .blocks_in_grp_1 = 3, .size_of_grp_1_blocks = 115, .blocks_in_grp_2 = 1, .size_of_grp_2_blocks = 116},
        entry{.version = 15, .ec_level = 'L', .total_data = 523, .ec_per_block = 22, .blocks_in_grp_1 = 5, .size_of_grp_1_blocks = 87, .blocks_in_grp_2 = 1, .size_of_grp_2_blocks = 88},
        entry{.version = 16, .ec_level = 'L', .total_data = 589, .ec_per_block = 24, .blocks_in_grp_1 = 5, .size_of_grp_1_blocks = 98, .blocks_in_grp_2 = 1, .size_of_grp_2_blocks = 99},
        entry{.version = 17, .ec_level = 'L', .total_data = 647, .ec_per_block = 28, .blocks_in_grp_1 = 1, .size_of_grp_1_blocks = 107, .blocks_in_grp_2 = 5, .size_of_grp_2_blocks = 108},
        entry{.version = 18, .ec_level = 'L', .total_data = 721, .ec_per_block = 30, .blocks_in_grp_1 = 5, .size_of_grp_1_blocks = 120, .blocks_in_grp_2 = 1, .size_of_grp_2_blocks = 121},
        entry{.version = 19, .ec_level = 'L', .total_data = 795, .ec_per_block = 28, .blocks_in_grp_1 = 3, .size_of_grp_1_blocks = 113, .blocks_in_grp_2 = 4, .size_of_grp_2_blocks = 114},
        entry{.version = 20, .ec_level = 'L', .total_data = 861, .ec_per_block = 28, .blocks_in_grp_1 = 3, .size_of_grp_1_blocks = 107, .blocks_in_grp_2 = 5, .size_of_grp_2_blocks = 108},
        entry{.version = 21, .ec_level = 'L', .total_data = 932, .ec_per_block = 28, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 116, .blocks_in_grp_2 = 4, .size_of_grp_2_blocks = 117},
        entry{.version = 22, .ec_level = 'L', .total_data = 1006, .ec_per_block = 28, .blocks_in_grp_1 = 2, .size_of_grp_1_blocks = 111, .blocks_in_grp_2 = 7, .size_of_grp_2_blocks = 112},
        entry{.version = 23, .ec_level = 'L', .total_data = 1094, .ec_per_block = 30, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 121, .blocks_in_grp_2 = 5, .size_of_grp_2_blocks = 122},
        entry{.version = 24, .ec_level = 'L', .total_data = 1174, .ec_per_block = 30, .blocks_in_grp_1 = 6, .size_of_grp_1_blocks = 117, .blocks_in_grp_2 = 4, .size_of_grp_2_blocks = 118},
        entry{.version = 25, .ec_level = 'L', .total_data = 1276, .ec_per_block = 26, .blocks_in_grp_1 = 8, .size_of_grp_1_blocks = 106, .blocks_in_grp_2 = 4, .size_of_grp_2_blocks = 107},
        entry{.version = 26, .ec_level = 'L', .total_data = 1370, .ec_per_block = 28, .blocks_in_grp_1 = 10, .size_of_grp_1_blocks = 114, .blocks_in_grp_2 = 2, .size_of_grp_2_blocks = 115},
        entry{.version = 27, .ec_level = 'L', .total_data = 1468, .ec_per_block = 30, .blocks_in_grp_1 = 8, .size_of_grp_1_blocks = 122, .blocks_in_grp_2 = 4, .size_of_grp_2_blocks = 123},
        entry{.version = 28, .ec_level = 'L', .total_data = 1531, .ec_per_block = 30, .blocks_in_grp_1 = 3, .size_of_grp_1_blocks = 117, .blocks_in_grp_2 = 10, .size_of_grp_2_blocks = 118},
        entry{.version = 29, .ec_level = 'L', .total_data = 1631, .ec_per_block = 30, .blocks_in_grp_1 = 7, .size_of_grp_1_blocks = 116, .blocks_in_grp_2 = 7, .size_of_grp_2_blocks = 117},
        entry{.version = 30, .ec_level = 'L', .total_data = 1735, .ec_per_block = 30, .blocks_in_grp_1 = 5, .size_of_grp_1_blocks = 115, .blocks_in_grp_2 = 10, .size_of_grp_2_blocks = 116},
        entry{.version = 31, .ec_level = 'L', .total_data = 1843, .ec_per_block = 30, .blocks_in_grp_1 = 13, .size_of_grp_1_blocks = 115, .blocks_in_grp_2 = 3, .size_of_grp_2_blocks = 116},
        entry{.version = 32, .ec_level = 'L', .total_data = 1955, .ec_per_block = 30, .blocks_in_grp_1 = 17, .size_of_grp_1_blocks = 115, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 33, .ec_level = 'L', .total_data = 2071, .ec_per_block = 30, .blocks_in_grp_1 = 17, .size_of_grp_1_blocks = 115, .blocks_in_grp_2 = 1, .size_of_grp_2_blocks = 116},
        entry{.version = 34, .ec_level = 'L', .total_data = 2191, .ec_per_block = 30, .blocks_in_grp_1 = 13, .size_of_grp_1_blocks = 115, .blocks_in_grp_2 = 6, .size_of_grp_2_blocks = 116},
        entry{.version = 35, .ec_level = 'L', .total_data = 2306, .ec_per_block = 30, .blocks_in_grp_1 = 12, .size_of_grp_1_blocks = 121, .blocks_in_grp_2 = 7, .size_of_grp_2_blocks = 122},
        entry{.version = 36, .ec_level = 'L', .total_data = 2434, .ec_per_block = 30, .blocks_in_grp_1 = 6, .size_of_grp_1_blocks = 121, .blocks_in_grp_2 = 14, .size_of_grp_2_blocks = 122},
        entry{.version = 37, .ec_level = 'L', .total_data = 2566, .ec_per_block = 30, .blocks_in_grp_1 = 17, .size_of_grp_1_blocks = 122, .blocks_in_grp_2 = 4, .size_of_grp_2_blocks = 123},
        entry{.version = 38, .ec_level = 'L', .total_data = 2702, .ec_per_block = 30, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 122, .blocks_in_grp_2 = 18, .size_of_grp_2_blocks = 123},
        entry{.version = 39, .ec_level = 'L', .total_data = 2812, .ec_per_block = 30, .blocks_in_grp_1 = 20, .size_of_grp_1_blocks = 117, .blocks_in_grp_2 = 4, .size_of_grp_2_blocks = 118},
        entry{.version = 40, .ec_level = 'L', .total_data = 2956, .ec_per_block = 30, .blocks_in_grp_1 = 19, .size_of_grp_1_blocks = 118, .blocks_in_grp_2 = 6, .size_of_grp_2_blocks = 119},
    };

    constexpr const std::array<entry, 40> medium_table = {
        entry{.version = 1, .ec_level = 'M', .total_data = 16, .ec_per_block = 10, .blocks_in_grp_1 = 1, .size_of_grp_1_blocks = 16, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 2, .ec_level = 'M', .total_data = 28, .ec_per_block = 16, .blocks_in_grp_1 = 1, .size_of_grp_1_blocks = 28, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 3, .ec_level = 'M', .total_data = 44, .ec_per_block = 26, .blocks_in_grp_1 = 1, .size_of_grp_1_blocks = 44, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 4, .ec_level = 'M', .total_data = 64, .ec_per_block = 18, .blocks_in_grp_1 = 2, .size_of_grp_1_blocks = 32, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 5, .ec_level = 'M', .total_data = 86, .ec_per_block = 24, .blocks_in_grp_1 = 2, .size_of_grp_1_blocks = 43, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 6, .ec_level = 'M', .total_data = 108, .ec_per_block = 16, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 27, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 7, .ec_level = 'M', .total_data = 124, .ec_per_block = 18, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 31, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 8, .ec_level = 'M', .total_data = 154, .ec_per_block = 22, .blocks_in_grp_1 = 2, .size_of_grp_1_blocks = 38, .blocks_in_grp_2 = 2, .size_of_grp_2_blocks = 39},
        entry{.version = 9, .ec_level = 'M', .total_data = 182, .ec_per_block = 22, .blocks_in_grp_1 = 3, .size_of_grp_1_blocks = 36, .blocks_in_grp_2 = 2, .size_of_grp_2_blocks = 37},
        entry{.version = 10, .ec_level = 'M', .total_data = 216, .ec_per_block = 26, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 43, .blocks_in_grp_2 = 1, .size_of_grp_2_blocks = 44},
        entry{.version = 11, .ec_level = 'M', .total_data = 254, .ec_per_block = 30, .blocks_in_grp_1 = 1, .size_of_grp_1_blocks = 50, .blocks_in_grp_2 = 4, .size_of_grp_2_blocks = 51},
        entry{.version = 12, .ec_level = 'M', .total_data = 290, .ec_per_block = 22, .blocks_in_grp_1 = 6, .size_of_grp_1_blocks = 36, .blocks_in_grp_2 = 2, .size_of_grp_2_blocks = 37},
        entry{.version = 13, .ec_level = 'M', .total_data = 334, .ec_per_block = 22, .blocks_in_grp_1 = 8, .size_of_grp_1_blocks = 37, .blocks_in_grp_2 = 1, .size_of_grp_2_blocks = 38},
        entry{.version = 14, .ec_level = 'M', .total_data = 365, .ec_per_block = 24, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 40, .blocks_in_grp_2 = 5, .size_of_grp_2_blocks = 41},
        entry{.version = 15, .ec_level = 'M', .total_data = 415, .ec_per_block = 24, .blocks_in_grp_1 = 5, .size_of_grp_1_blocks = 41, .blocks_in_grp_2 = 5, .size_of_grp_2_blocks = 42},
        entry{.version = 16, .ec_level = 'M', .total_data = 453, .ec_per_block = 28, .blocks_in_grp_1 = 7, .size_of_grp_1_blocks = 45, .blocks_in_grp_2 = 3, .size_of_grp_2_blocks = 46},
        entry{.version = 17, .ec_level = 'M', .total_data = 507, .ec_per_block = 28, .blocks_in_grp_1 = 10, .size_of_grp_1_blocks = 46, .blocks_in_grp_2 = 1, .size_of_grp_2_blocks = 47},
        entry{.version = 18, .ec_level = 'M', .total_data = 563, .ec_per_block = 26, .blocks_in_grp_1 = 9, .size_of_grp_1_blocks = 43, .blocks_in_grp_2 = 4, .size_of_grp_2_blocks = 44},
        entry{.version = 19, .ec_level = 'M', .total_data = 627, .ec_per_block = 26, .blocks_in_grp_1 = 3, .size_of_grp_1_blocks = 44, .blocks_in_grp_2 = 11, .size_of_grp_2_blocks = 45},
        entry{.version = 20, .ec_level = 'M', .total_data = 669, .ec_per_block = 26, .blocks_in_grp_1 = 3, .size_of_grp_1_blocks = 41, .blocks_in_grp_2 = 13, .size_of_grp_2_blocks = 42},
        entry{.version = 21, .ec_level = 'M', .total_data = 714, .ec_per_block = 26, .blocks_in_grp_1 = 17, .size_of_grp_1_blocks = 42, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 22, .ec_level = 'M', .total_data = 782, .ec_per_block = 28, .blocks_in_grp_1 = 17, .size_of_grp_1_blocks = 46, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 23, .ec_level = 'M', .total_data = 860, .ec_per_block = 28, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 47, .blocks_in_grp_2 = 14, .size_of_grp_2_blocks = 48},
        entry{.version = 24, .ec_level = 'M', .total_data = 914, .ec_per_block = 28, .blocks_in_grp_1 = 6, .size_of_grp_1_blocks = 45, .blocks_in_grp_2 = 14, .size_of_grp_2_blocks = 46},
        entry{.version = 25, .ec_level = 'M', .total_data = 1000, .ec_per_block = 28, .blocks_in_grp_1 = 8, .size_of_grp_1_blocks = 47, .blocks_in_grp_2 = 13, .size_of_grp_2_blocks = 48},
        entry{.version = 26, .ec_level = 'M', .total_data = 1062, .ec_per_block = 28, .blocks_in_grp_1 = 19, .size_of_grp_1_blocks = 46, .blocks_in_grp_2 = 4, .size_of_grp_2_blocks = 47},
        entry{.version = 27, .ec_level = 'M', .total_data = 1128, .ec_per_block = 28, .blocks_in_grp_1 = 22, .size_of_grp_1_blocks = 45, .blocks_in_grp_2 = 3, .size_of_grp_2_blocks = 46},
        entry{.version = 28, .ec_level = 'M', .total_data = 1193, .ec_per_block = 28, .blocks_in_grp_1 = 3, .size_of_grp_1_blocks = 45, .blocks_in_grp_2 = 23, .size_of_grp_2_blocks = 46},
        entry{.version = 29, .ec_level = 'M', .total_data = 1267, .ec_per_block = 28, .blocks_in_grp_1 = 21, .size_of_grp_1_blocks = 45, .blocks_in_grp_2 = 7, .size_of_grp_2_blocks = 46},
        entry{.version = 30, .ec_level = 'M', .total_data = 1373, .ec_per_block = 28, .blocks_in_grp_1 = 19, .size_of_grp_1_blocks = 47, .blocks_in_grp_2 = 10, .size_of_grp_2_blocks = 48},
        entry{.version = 31, .ec_level = 'M', .total_data = 1455, .ec_per_block = 28, .blocks_in_grp_1 = 2, .size_of_grp_1_blocks = 46, .blocks_in_grp_2 = 29, .size_of_grp_2_blocks = 47},
        entry{.version = 32, .ec_level = 'M', .total_data = 1541, .ec_per_block = 28, .blocks_in_grp_1 = 10, .size_of_grp_1_blocks = 46, .blocks_in_grp_2 = 23, .size_of_grp_2_blocks = 47},
        entry{.version = 33, .ec_level = 'M', .total_data = 1631, .ec_per_block = 28, .blocks_in_grp_1 = 14, .size_of_grp_1_blocks = 46, .blocks_in_grp_2 = 21, .size_of_grp_2_blocks = 47},
        entry{.version = 34, .ec_level = 'M', .total_data = 1725, .ec_per_block = 28, .blocks_in_grp_1 = 14, .size_of_grp_1_blocks = 46, .blocks_in_grp_2 = 23, .size_of_grp_2_blocks = 47},
        entry{.version = 35, .ec_level = 'M', .total_data = 1812, .ec_per_block = 28, .blocks_in_grp_1 = 12, .size_of_grp_1_blocks = 47, .blocks_in_grp_2 = 26, .size_of_grp_2_blocks = 48},
        entry{.version = 36, .ec_level = 'M', .total_data = 1914, .ec_per_block = 28, .blocks_in_grp_1 = 6, .size_of_grp_1_blocks = 47, .blocks_in_grp_2 = 34, .size_of_grp_2_blocks = 48},
        entry{.version = 37, .ec_level = 'M', .total_data = 1992, .ec_per_block = 28, .blocks_in_grp_1 = 29, .size_of_grp_1_blocks = 46, .blocks_in_grp_2 = 14, .size_of_grp_2_blocks = 47},
        entry{.version = 38, .ec_level = 'M', .total_data = 2102, .ec_per_block = 28, .blocks_in_grp_1 = 13, .size_of_grp_1_blocks = 46, .blocks_in_grp_2 = 32, .size_of_grp_2_blocks = 47},
        entry{.version = 39, .ec_level = 'M', .total_data = 2216, .ec_per_block = 28, .blocks_in_grp_1 = 40, .size_of_grp_1_blocks = 47, .blocks_in_grp_2 = 7, .size_of_grp_2_blocks = 48},
        entry{.version = 40, .ec_level = 'M', .total_data = 2334, .ec_per_block = 28, .blocks_in_grp_1 = 18, .size_of_grp_1_blocks = 47, .blocks_in_grp_2 = 31, .size_of_grp_2_blocks = 48},
    };

    constexpr const std::array<entry, 40> quartile_table = {
        entry{.version = 1, .ec_level = 'Q', .total_data = 13, .ec_per_block = 13, .blocks_in_grp_1 = 1, .size_of_grp_1_blocks = 13, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 2, .ec_level = 'Q', .total_data = 22, .ec_per_block = 22, .blocks_in_grp_1 = 1, .size_of_grp_1_blocks = 22, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 3, .ec_level = 'Q', .total_data = 34, .ec_per_block = 18, .blocks_in_grp_1 = 2, .size_of_grp_1_blocks = 17, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 4, .ec_level = 'Q', .total_data = 48, .ec_per_block = 26, .blocks_in_grp_1 = 2, .size_of_grp_1_blocks = 24, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 5, .ec_level = 'Q', .total_data = 62, .ec_per_block = 18, .blocks_in_grp_1 = 2, .size_of_grp_1_blocks = 15, .blocks_in_grp_2 = 2, .size_of_grp_2_blocks = 16},
        entry{.version = 6, .ec_level = 'Q', .total_data = 76, .ec_per_block = 24, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 19, .blocks_in_grp_2 = 0, .size_of_grp_2_blocks = 0},
        entry{.version = 7, .ec_level = 'Q', .total_data = 88, .ec_per_block = 18, .blocks_in_grp_1 = 2, .size_of_grp_1_blocks = 14, .blocks_in_grp_2 = 4, .size_of_grp_2_blocks = 15},
        entry{.version = 8, .ec_level = 'Q', .total_data = 110, .ec_per_block = 22, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 18, .blocks_in_grp_2 = 2, .size_of_grp_2_blocks = 19},
        entry{.version = 9, .ec_level = 'Q', .total_data = 132, .ec_per_block = 20, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 16, .blocks_in_grp_2 = 4, .size_of_grp_2_blocks = 17},
        entry{.version = 10, .ec_level = 'Q', .total_data = 154, .ec_per_block = 24, .blocks_in_grp_1 = 6, .size_of_grp_1_blocks = 19, .blocks_in_grp_2 = 2, .size_of_grp_2_blocks = 20},
        entry{.version = 11, .ec_level = 'Q', .total_data = 180, .ec_per_block = 28, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 22, .blocks_in_grp_2 = 4, .size_of_grp_2_blocks = 23},
        entry{.version = 12, .ec_level = 'Q', .total_data = 206, .ec_per_block = 26, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 20, .blocks_in_grp_2 = 6, .size_of_grp_2_blocks = 21},
        entry{.version = 13, .ec_level = 'Q', .total_data = 244, .ec_per_block = 24, .blocks_in_grp_1 = 8, .size_of_grp_1_blocks = 20, .blocks_in_grp_2 = 4, .size_of_grp_2_blocks = 21},
        entry{.version = 14, .ec_level = 'Q', .total_data = 261, .ec_per_block = 20, .blocks_in_grp_1 = 11, .size_of_grp_1_blocks = 16, .blocks_in_grp_2 = 5, .size_of_grp_2_blocks = 17},
        entry{.version = 15, .ec_level = 'Q', .total_data = 295, .ec_per_block = 30, .blocks_in_grp_1 = 5, .size_of_grp_1_blocks = 24, .blocks_in_grp_2 = 7, .size_of_grp_2_blocks = 25},
        entry{.version = 16, .ec_level = 'Q', .total_data = 325, .ec_per_block = 24, .blocks_in_grp_1 = 15, .size_of_grp_1_blocks = 19, .blocks_in_grp_2 = 2, .size_of_grp_2_blocks = 20},
        entry{.version = 17, .ec_level = 'Q', .total_data = 367, .ec_per_block = 28, .blocks_in_grp_1 = 1, .size_of_grp_1_blocks = 22, .blocks_in_grp_2 = 15, .size_of_grp_2_blocks = 23},
        entry{.version = 18, .ec_level = 'Q', .total_data = 397, .ec_per_block = 28, .blocks_in_grp_1 = 17, .size_of_grp_1_blocks = 22, .blocks_in_grp_2 = 1, .size_of_grp_2_blocks = 23},
        entry{.version = 19, .ec_level = 'Q', .total_data = 445, .ec_per_block = 26, .blocks_in_grp_1 = 17, .size_of_grp_1_blocks = 21, .blocks_in_grp_2 = 4, .size_of_grp_2_blocks = 22},
        entry{.version = 20, .ec_level = 'Q', .total_data = 485, .ec_per_block = 30, .blocks_in_grp_1 = 15, .size_of_grp_1_blocks = 24, .blocks_in_grp_2 = 5, .size_of_grp_2_blocks = 25},
        entry{.version = 21, .ec_level = 'Q', .total_data = 512, .ec_per_block = 28, .blocks_in_grp_1 = 17, .size_of_grp_1_blocks = 22, .blocks_in_grp_2 = 6, .size_of_grp_2_blocks = 23},
        entry{.version = 22, .ec_level = 'Q', .total_data = 568, .ec_per_block = 30, .blocks_in_grp_1 = 7, .size_of_grp_1_blocks = 24, .blocks_in_grp_2 = 16, .size_of_grp_2_blocks = 25},
        entry{.version = 23, .ec_level = 'Q', .total_data = 614, .ec_per_block = 30, .blocks_in_grp_1 = 11, .size_of_grp_1_blocks = 24, .blocks_in_grp_2 = 14, .size_of_grp_2_blocks = 25},
        entry{.version = 24, .ec_level = 'Q', .total_data = 664, .ec_per_block = 30, .blocks_in_grp_1 = 11, .size_of_grp_1_blocks = 24, .blocks_in_grp_2 = 16, .size_of_grp_2_blocks = 25},
        entry{.version = 25, .ec_level = 'Q', .total_data = 718, .ec_per_block = 30, .blocks_in_grp_1 = 7, .size_of_grp_1_blocks = 24, .blocks_in_grp_2 = 22, .size_of_grp_2_blocks = 25},
        entry{.version = 26, .ec_level = 'Q', .total_data = 754, .ec_per_block = 28, .blocks_in_grp_1 = 28, .size_of_grp_1_blocks = 22, .blocks_in_grp_2 = 6, .size_of_grp_2_blocks = 23},
        entry{.version = 27, .ec_level = 'Q', .total_data = 808, .ec_per_block = 30, .blocks_in_grp_1 = 8, .size_of_grp_1_blocks = 23, .blocks_in_grp_2 = 26, .size_of_grp_2_blocks = 24},
        entry{.version = 28, .ec_level = 'Q', .total_data = 871, .ec_per_block = 30, .blocks_in_grp_1 = 4, .size_of_grp_1_blocks = 24, .blocks_in_grp_2 = 31, .size_of_grp_2_blocks = 25},
        entry{.version = 29, .ec_level = 'Q', .total_data = 911, .ec_per_block = 30, .blocks_in_grp_1 = 1, .size_of_grp_1_blocks = 23, .blocks_in_grp_2 = 37, .size_of_grp_2_blocks = 24},
        entry{.version = 30, .ec_level = 'Q', .total_data = 985, .ec_per_block = 30, .blocks_in_grp_1 = 15, .size_of_grp_1_blocks = 24, .blocks_in_grp_2 = 25, .size_of_grp_2_blocks = 25},
        entry{.version = 31, .ec_level = 'Q', .total_data = 1033, .ec_per_block = 30, .blocks_in_grp_1 = 42, .size_of_grp_1_blocks = 24, .blocks_in_grp_2 = 1, .size_of_grp_2_blocks = 25},
        entry{.version = 32, .ec_level = 'Q', .total_data = 1115, .ec_per_block = 30, .blocks_in_grp_1 = 10, .size_of_grp_1_blocks = 24, .blocks_in_grp_2 = 35, .size_of_grp_2_blocks = 25},
        entry{.version = 33, .ec_level = 'Q', .total_data = 1171, .ec_per_block = 30, .blocks_in_grp_1 = 29, .size_of_grp_1_blocks = 24, .blocks_in_grp_2 = 19, .size_of_grp_2_blocks = 25},
        entry{.version = 34, .ec_level = 'Q', .total_data = 1231, .ec_per_block = 30, .blocks_in_grp_1 = 44, .size_of_grp_1_blocks = 24, .blocks_in_grp_2 = 7, .size_of_grp_2_blocks = 25},
        entry{.version = 35, .ec_level = 'Q', .total_data = 1286, .ec_per_block = 30, .blocks_in_grp_1 = 39, .size_of_grp_1_blocks = 24, .blocks_in_grp_2 = 14, .size_of_grp_2_blocks = 25},
        entry{.version = 36, .ec_level = 'Q', .total_data = 1354, .ec_per_block = 30, .blocks_in_grp_1 = 46, .size_of_grp_1_blocks = 24, .blocks_in_grp_2 = 10, .size_of_grp_2_blocks = 25},
        entry{.version = 37, .ec_level = 'Q', .total_data = 1426, .ec_per_block = 30, .blocks_in_grp_1 = 49, .size_of_grp_1_blocks = 24, .blocks_in_grp_2 = 10, .size_of_grp_2_blocks = 25},
        entry{.version = 38, .ec_level = 'Q', .total_data = 1502, .ec_per_block = 30, .blocks_in_grp_1 = 48, .size_of_grp_1_blocks = 24, .blocks_in_grp_2 = 14, .size_of_grp_2_blocks = 25},
        entry{.version = 39, .ec_level = 'Q', .total_data = 1582, .ec_per_block = 30, .blocks_in_grp_1 = 43, .size_of_grp_1_blocks = 24, .blocks_in_grp_2 = 22, .size_of_grp_2_blocks = 25},
        entry{.version = 40, .ec_level = 'Q', .total_data = 1666, .ec_per_block = 30, .blocks_in_grp_1 = 34, .size_of_grp_1_blocks = 24, .blocks_in_grp_2 = 34, .size_of_grp_2_blocks = 25},
    };

    std::optional<entry> search(const int msg_words, const char level);
};
